import uuid
import pytest
from backend.app.rag.router import query_router, QueryRoute
from backend.app.rag.rewriter import query_rewriter
from backend.app.rag.hyde import hyde_generator
from backend.app.rag.reranker import reranker
from backend.app.rag.corrective import corrective_rag
from backend.app.rag.generator import answer_generator
from backend.app.rag.pipeline import rag_pipeline
from backend.app.services.vector_service import vector_service
from backend.app.schemas.document import ChunkMetadata
from backend.app.schemas.rag import ScoredChunk


def test_query_router_heuristic_and_classification():
    # Follow-up with pronoun should route to REWRITE
    history = [
        {"role": "user", "content": "Tell me about the OAuth2 system."},
        {"role": "assistant", "content": "OAuth2 issues JWT tokens signed with HS256."}
    ]
    route1 = query_router.route("How does it expire?", conversation_history=history)
    assert route1 == QueryRoute.REWRITE

    # Direct standalone question with no history
    route2 = query_router.route("What is the maximum file upload size?", conversation_history=[])
    assert route2 in [QueryRoute.DIRECT_QA, QueryRoute.HYDE]


def test_cross_encoder_reranker():
    user_id = uuid.uuid4()
    kb_id = uuid.uuid4()
    doc_id = uuid.uuid4()

    chunks = [
        ScoredChunk(
            chunk_id="chunk_irrelevant",
            document_id=doc_id,
            user_id=user_id,
            knowledge_base_id=kb_id,
            filename="cooking.txt",
            page_number=1,
            chunk_index=0,
            text="Baking a chocolate cake requires flour, cocoa powder, sugar, and eggs.",
            score=0.5,
            retrieval_type="hybrid"
        ),
        ScoredChunk(
            chunk_id="chunk_relevant",
            document_id=doc_id,
            user_id=user_id,
            knowledge_base_id=kb_id,
            filename="security.txt",
            page_number=1,
            chunk_index=1,
            text="User passwords are encrypted with bcrypt and access tokens expire after 24 hours.",
            score=0.6,
            retrieval_type="hybrid"
        )
    ]

    reranked = reranker.rerank(
        query="How are passwords protected and when do tokens expire?",
        chunks=chunks,
        top_k=2
    )

    assert len(reranked) == 2
    # The security chunk must be ranked #1 by the cross-encoder
    assert reranked[0].chunk_id == "chunk_relevant"
    assert reranked[0].retrieval_type == "reranked"


def test_corrective_rag_evaluation():
    user_id = uuid.uuid4()
    kb_id = uuid.uuid4()
    doc_id = uuid.uuid4()

    # Empty chunks -> insufficient
    status, retry = corrective_rag.evaluate_context(
        query="What is the server port?",
        chunks=[],
        attempt=1
    )
    assert status == "INSUFFICIENT"
    assert retry is True

    # Highly relevant chunk
    chunk = ScoredChunk(
        chunk_id="c1",
        document_id=doc_id,
        user_id=user_id,
        knowledge_base_id=kb_id,
        filename="config.txt",
        page_number=1,
        chunk_index=0,
        text="The FastAPI backend server runs on host 0.0.0.0 and port 8000.",
        score=2.5,
        retrieval_type="reranked"
    )
    status_rel, retry_rel = corrective_rag.evaluate_context(
        query="What port does FastAPI run on?",
        chunks=[chunk],
        attempt=1
    )
    assert status_rel == "RELEVANT"
    assert retry_rel is False


def test_full_rag_pipeline_execution():
    user_id = uuid.uuid4()
    kb_id = uuid.uuid4()
    doc_id = uuid.uuid4()
    conv_id = uuid.uuid4()

    chunks = [
        ChunkMetadata(
            chunk_id=f"{doc_id}_p1_c0",
            document_id=doc_id,
            user_id=user_id,
            knowledge_base_id=kb_id,
            filename="enterprise_policy.txt",
            page_number=1,
            chunk_index=0,
            text="The maximum document file size allowed in the knowledge assistant is 25 Megabytes."
        ),
        ChunkMetadata(
            chunk_id=f"{doc_id}_p1_c1",
            document_id=doc_id,
            user_id=user_id,
            knowledge_base_id=kb_id,
            filename="enterprise_policy.txt",
            page_number=1,
            chunk_index=1,
            text="Qdrant vector database stores dense embeddings generated by BAAI/bge-small-en-v1.5."
        )
    ]
    vector_service.upsert_chunks(chunks)

    response = rag_pipeline.execute(
        query="What is the maximum file size for document uploads?",
        user_id=user_id,
        kb_id=kb_id,
        conversation_id=conv_id,
        conversation_history=[]
    )

    assert response.conversation_id == conv_id
    assert response.answer is not None
    assert len(response.citations) > 0
    assert response.citations[0].document_name == "enterprise_policy.txt"
    assert response.metadata["candidates_retrieved"] > 0
    assert response.metadata["route"] is not None
